### ISSUE TITLE
OMPL File

### ISSUE THREAD

**Issue by mik-laj** [douglasdollars/gcp-release-notes-feeds#3]
Hello,

It would be fantastic if an OPML file were created with all the information. This will allow you to easily and automatically add these files to readers.
https://en.wikipedia.org/wiki/OPML

Regards.

**Comment by douglasdollars** [comment]
I agree. http://cloud.google.com/release-notes will be the page receiving ongoing support and feeds. This was/is just a hobby resource in the meantime- I'm not affiliated with the team making the official page.
